name: Node.js and MySQL CI/CD (Windows)

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Deploy to Server
        run: |
          # Replace with your deployment commands for Windows environment

          # Example: Deploy using PowerShell
          # .\deploy.ps1

          # Example: MySQL Configuration (if needed)
          # Replace <your-mysql-connection-details> with your actual MySQL connection details
          # .\mysql.exe -u <username> -p<password> -h <hostname> -e "CREATE DATABASE IF NOT EXISTS <database_name>"

          # Add more deployment and MySQL commands as needed
